// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anfiqtobitltcdydifnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuZmlxdG9iaXRsdGNkeWRpZm5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5ODU0MzEsImV4cCI6MjA3NzU2MTQzMX0.EDcPu9a6SYJqAmqs2JanL_jG6i4Ll8mNvcxV-LiUgYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
